Default_Background: "https://coolbackgrounds.io/images/backgrounds/black/pure-black-background-f82588d3.jpg"
Default_XP_Colour: "#ffffff"
Default_Border: "https://coolbackgrounds.io/images/backgrounds/black/pure-black-background-f82588d3.jpg"
